// Pumpunjuksautin interface functions.
//
// SPDX-License-Identifier:   GPL-3.0-or-later
// Copyright (C) 2021 Joel Lehtonen
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#include <stdio.h>
#include <time.h>
#include <string.h>
#include <avr/io.h>
#include <avr/pgmspace.h>
#include "cmd.h"
#include "../pin.h"
#include "../hardware_config.h"
#include "../byteswap.h"

const cmd_result_t cmd_scan_success = { 0, NULL, 0 };

// Functions are used by external commands via Modbus or ASCII command
// interface, defined in file avr/commands.tsv.
//
// The prefix "cmd_" is added automatically to the function names in
// the table. So, "write_led" in the table maps to "cmd_write_led" in
// this object.
//
// Functions used in the table in commands.tsv do not require
// prototypes because those are auto-generated by `commands` script.

static cmd_modbus_result_t modbus_unaligned();
static cmd_modbus_result_t modbus_pass(buflen_t consumed, modbus_status_t ret);
static char const *modbus_strerror(modbus_status_t e);

// Scans input for boolean values. Accepting true, false, 0, and 1.
cmd_result_t cmd_scan_bool(char *const buf_in, void *setter)
{
	bool val;
	if (strcasecmp_P(buf_in, PSTR("on")) == 0) {
		val = true;
	} else if (strcasecmp_P(buf_in, PSTR("off")) == 0) {
		val = false;
	} else if (strcmp_P(buf_in, PSTR("1")) == 0) {
		val = true;
	} else if (strcmp_P(buf_in, PSTR("0")) == 0) {
		val = false;
	} else {
		// Parsing failed
		const cmd_result_t e = {0, PSTR("Allowed values: 0, 1, ON, or OFF"), 0};
		return e;
	}

	// Pass it on setter
	set_bool_t *f = setter;
	modbus_status_t status = f(val);
	if (status == MODBUS_OK) {
		return cmd_scan_success;
	} else {
		const cmd_result_t e = {0, modbus_strerror(status), status};
		return e;
	}
}

// Scans input for a single 16 bit integer, signed or unsigned.
cmd_result_t cmd_scan_int16(char *const buf_in, void *setter)
{
	int read = 0;
	int16_t val;
	int items = sscanf_P(buf_in, PSTR("%" SCNi16 "%n"), &val, &read);
	if (items != 1 || buf_in[read] != '\0') {
		const cmd_result_t e = { read, PSTR("Not a digit"), 0};
		return e;
	}

	// Pass it on setter
	set_int16_t *f = setter;
	modbus_status_t status = f(val);
	if (status == MODBUS_OK) {
		return cmd_scan_success;
	} else {
		const cmd_result_t e = {0, modbus_strerror(status), status};
		return e;
	}
}

// Scans input for a single 32 bit integer, signed or unsigned.
cmd_result_t cmd_scan_int32(char *const buf_in, void *setter)
{
	int read = 0;
	int32_t val;
	int items = sscanf_P(buf_in, PSTR("%" SCNi32 "%n"), &val, &read);
	if (items != 1 || buf_in[read] != '\0') {
		const cmd_result_t e = { read, PSTR("Not a digit"), 0};
		return e;
	}

	// Pass it on setter
	set_int32_t *f = setter;
	modbus_status_t status = f(val);
	if (status == MODBUS_OK) {
		return cmd_scan_success;
	} else {
		const cmd_result_t e = {0, modbus_strerror(status), status};
		return e;
	}
}

// Outputs boolean value.
buflen_t cmd_print_bool(char *const buf_out, buflen_t count, void *getter)
{
	if (count < 1) return BUFLEN_MAX;

	get_bool_t *f = getter;
	*buf_out = f() ? '1' : '0';
	return 1;
}

// Gets and prints 16-bit signed integer in decimal format
buflen_t cmd_print_int16(char *const buf_out, buflen_t count, void *getter)
{
	get_int16_t *f = getter;
	return snprintf_P(buf_out, count, PSTR("%" PRId16), f());
}

// Gets and prints 32-bit signed integer in decimal format.
buflen_t cmd_print_int32(char *const buf_out, buflen_t count, void *getter)
{
	get_int32_t *f = getter;
	return snprintf_P(buf_out, count, PSTR("%" PRId32), f());
}

// Basically just a wrapper for printing strings.
buflen_t cmd_print_string(char *const buf_out, buflen_t count, void *getter)
{
	get_string_t *f = getter;
	return f(buf_out, count);
}

// Reads a single 16 bit big endian integer, signed or unsigned.
cmd_modbus_result_t cmd_bin_read_int16(char *const buf_out, buflen_t count, void *getter)
{
	if (count < sizeof(int16_t)) return modbus_unaligned();

	// Get the value and swap endianness to big endian
	get_int16_t *f = getter;
	int16_t *buf = (int16_t*)buf_out;
	*buf = bswap_16(f());

	return modbus_pass(sizeof(int16_t), MODBUS_OK);
}

// Reads a single 32 bit big endian integer, signed or unsigned.
cmd_modbus_result_t cmd_bin_read_int32(char *const buf_out, buflen_t count, void *getter)
{
	if (count < sizeof(int32_t)) return modbus_unaligned();

	// Get the value and swap endianness to big endian
	get_int32_t *f = getter;
	int32_t *buf = (int32_t*)buf_out;
	*buf = bswap_32(f());

	return modbus_pass(sizeof(int32_t), MODBUS_OK);
}

// Writes a single 16 bit big endian integer, signed or unsigned.
cmd_modbus_result_t cmd_bin_write_int16(char const *const buf_in, buflen_t count, void *setter)
{
	if (count < sizeof(int16_t)) return modbus_unaligned();

	// Get value from big-endian format
	int16_t val = bswap_16(*(int16_t*)buf_in);

	// Pass it on setter
	set_int16_t *f = setter;
	return modbus_pass(sizeof(int16_t), f(val));
}

// Writes a single 32 bit big endian integer, signed or unsigned.
cmd_modbus_result_t cmd_bin_write_int32(char const *const buf_in, buflen_t count, void *setter)
{
	if (count < sizeof(int32_t)) return modbus_unaligned();

	// Get value from big-endian format
	int32_t val = bswap_32(*(int32_t*)buf_in);

	// Pass it on setter
	set_int32_t *f = setter;
	return modbus_pass(sizeof(int32_t), f(val));
}

static cmd_modbus_result_t modbus_unaligned()
{
	// Byte alignment error
	return modbus_pass(0, MODBUS_EXCEPTION_ILLEGAL_DATA_ADDRESS);
}

static cmd_modbus_result_t modbus_pass(buflen_t consumed, modbus_status_t ret)
{
	// Pass the result with the return code
	cmd_modbus_result_t a = { ret, consumed};
	return a;
}

static char const *modbus_strerror(modbus_status_t e)
{
	switch (e) {
	case MODBUS_OK: return NULL; // All is fine
	case MODBUS_EXCEPTION_ILLEGAL_DATA_VALUE: return PSTR("Illegal data value");
	case MODBUS_EXCEPTION_SLAVE_OR_SERVER_FAILURE: return PSTR("Unrecoverable error");
	default: return PSTR("Modbus error %d");
	}
}
